name: Gatsby Publish

on:
  push:
    branches:
      - main
    paths: 
      - 'site/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ github.event_name }}
