name: PR update

on:
    push:
        branches: 
            - main

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: update all prs
          uses: Merciful12/pr-updater-action@1
          with:
            token: ${{ secrets.USD }}
