name: PR update

on:
    push:
        branches: 
            - main

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Automatically update PR
          uses: adRise/update-pr-branch@v0.6.0
          with:
              token: ${{ secrets.USD }}
              base: 'main'
              required_approval_count: 0
              require_passed_checks: false
